######################################## 
#              Timings:                # 
#         Loging timings on/off        # 
#                                      # 
#              Updater:                # 
#           Enable outo update         # 
#                                      # 
#             ByteBuffType:            # 
#  The Used Buffer type for Packets    # 
#              Avariable:              # 
#    - 'direct'                        # 
#    - 'heap'                          # 
#                                      # 
#               Terminal:              # 
#      Colors in terminal on/off       # 
#                                      # 
#            Async-Catcher:            # 
#  Enable it for more packet security  # 
#        The catcher has 2 modes:      # 
# - EXCEPTION (will throw a exception) # 
# - WARNING (will print a warn message)# 
#                                      #
#             Debug messages           #
#   Enable/Disable all debug messages  #  
#                                      # 
#               Utils:                 # 
#  Enable/Disable some unused feature  #  
#             to save ram              #  
#                                      # 
#                                      # 
#        Handle Exception Action:      # 
#        DISCONNECT, PRINT, NONE       #  
######################################## 
timings: true
updater: true
byteBuffType: direct
system.gc:
  enabled: false
  periode: 60000
terminal:
  colored: true
debug:
  ram-statistics: true
  messages: true
loading:
  inject:
    buffer-size: 65536
  fastboot: false
  quiet: false
async-catcher:
  enabled: true
  mode: EXCEPTION
inventory:
  synchandle: true
utils:
  scoreboard: true
  bossbar: true
network:
  exception: DISCONNECT
